sid: 12201

dev: true
debug: true

grpc:
  listen_addr: 127.0.0.1:8300
  link_addr: 127.0.0.1:8300

redis:
  addrs:
    - 127.0.0.1:7000
    - 127.0.0.1:7001
    - 127.0.0.1:7002
    - 127.0.0.1:7003
    - 127.0.0.1:7004
    - 127.0.0.1:7005
  addr: 127.0.0.1:7100
  pass: f2bc5b4031bc45805c3a31ce916b6bea

mongo:
  uri: mongodb://admin:ASDF)&(*H123498-FQEW@127.0.0.1:27017
  #uri: mongodb://localhost:27017/
  db: mokoko_thunder

table:
  path: ../comm/t_config
telegram:
  login_token: 7492635198:AAFTNaXiRCpERqAQBaXOC3q2hRHAoqrUvpQ
#  login_token: 7114786236:AAGaW4WhHhp-z0tJfOEMLb5CXu3q_Fa8_Wk
  listen_dev:
    #    - name: rtest_dev_bot
    #      token: 7492635198:AAFTNaXiRCpERqAQBaXOC3q2hRHAoqrUvpQ
    #      chat_ids: [ -1002209798428 ]
    # 甲方
    - name: SoSoValue
      token: 7145824162:AAGlaL7Ral7jetDG8MoU_N4b-P0fLUucInA
      chat_ids: [ -1001765198458 ]
    - name: SafePal
      token: 7145824162:AAGlaL7Ral7jetDG8MoU_N4b-P0fLUucInA
      chat_ids: [ -1001937794848 ]
    - name: SoSoValueBot
      token: test
      chat_ids: [ ]
    - name: twitter
      token: 123
      chat_ids: [ ]
  listen:
    - name: SoSoValue
      token: 7145824162:AAGlaL7Ral7jetDG8MoU_N4b-P0fLUucInA
      chat_ids: [ -1001765198458 ]
    - name: SafePal
      token: 7145824162:AAGlaL7Ral7jetDG8MoU_N4b-P0fLUucInA
      chat_ids: [ -1001937794848 ]
    - name: SoSoValueBot
      token: test
      chat_ids: [ ]
    - name: twitter
      token: 123
      chat_ids: [ ]
