service: goLearn

elastic:
  use: false
#  host: http://192.168.20.77
  host: http://192.168.20.24
  port: 9200

mongo:
  use: true
  uri: mongodb://admin:123456@127.0.0.1:27017
  db: platform

version: 1
time: 2023-10-12 14:42:00